name: env-electron-python2
channels:
- defaults
- conda-forge
dependencies:
- python = 3.6
- PyInstaller = 3.5
- nodejs = 10.13.0
- libgcc = 7.2.0
- git = 2.20.1
- pyyaml = 5.4.1
- pip
- pip:
  # pin older version of setuptools to fix this error:
  #   ModuleNotFoundError: No module named 'pkg_resources.py2_warn'
  # see: https://github.com/pypa/setuptools/issues/1963#issuecomment-573675633
  - setuptools < 45.0.0
  - pandas == 0.25.2
  - openpyxl == 3.0.0
  - zerorpc == 0.6.3
  - pennsieve == 6.1.2
  - configparser == 4.0.2
  - python-docx == 0.8.10
  - xlrd == 1.2.0
  - ipython == 7.24.1
  - git+https://github.com/tgbugs/augpathlib
  - git+https://github.com/tgbugs/idlib
  - git+https://github.com/tgbugs/hyputils
  - git+https://github.com/tgbugs/orthauth
  - git+https://github.com/tgbugs/ontquery
  - git+https://github.com/tgbugs/parsercomb
  - git+https://github.com/tgbugs/pyontutils
  - protcur == 0.0.8
  - git+https://github.com/SciCrunch/scibot
  - git+https://github.com/SciCrunch/sparc-curation
